# Generated by Django 4.1.2 on 2022-12-02 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0001_initial"),
        ("checkout_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="orderlineitem",
            name="image",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="shop_app.image",
            ),
        ),
    ]
