# Generated by Django 4.1.2 on 2022-11-17 18:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_app", "0001_initial"),
        ("checkout_app", "0002_alter_order_country"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="user_profile",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="orders",
                to="profiles_app.userprofile",
            ),
        ),
    ]
