# Generated by Django 4.1.2 on 2022-10-10 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="image",
            field=models.ImageField(default="default.png", upload_to="book_covers"),
        ),
    ]
