# Generated by Django 4.1.2 on 2022-12-15 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                default="default_covers/no_cover.png", upload_to="book_covers/"
            ),
        ),
    ]
