# Generated by Django 4.1.2 on 2022-11-18 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="publication_date",
            field=models.DateField(
                null=True, verbose_name="Date the book was published."
            ),
        ),
    ]
