# Generated by Django 4.1.2 on 2022-12-06 01:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="book",
            old_name="genre",
            new_name="genres",
        ),
        migrations.AlterField(
            model_name="author",
            name="first_name",
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name="author",
            name="last_name",
            field=models.CharField(max_length=50),
        ),
    ]
