# Generated by Django 4.1.2 on 2022-12-11 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0002_rename_genre_book_genres_alter_author_first_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="book",
            name="pages",
            field=models.PositiveIntegerField(null=True),
        ),
    ]
