# Generated by Django 4.1.2 on 2022-10-10 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("shop_app", "0003_image_book_number_in_stock_alter_book_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                blank=True, default="default.png", null=True, upload_to="book_covers"
            ),
        ),
    ]
