# Generated by Django 4.1.2 on 2022-12-11 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_app", "0001_initial"),
        ("shop_app", "0003_alter_book_pages"),
    ]

    operations = [
        migrations.AddField(
            model_name="book",
            name="users_wishlist",
            field=models.ManyToManyField(
                blank=True,
                null=True,
                related_name="user_wishlist",
                to="profiles_app.userprofile",
            ),
        ),
    ]
