# Generated by Django 4.1.2 on 2022-12-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("profiles_app", "0002_wishlist"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="default_full_name",
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
